### This demo shows how to perform filtering on a simple 
### synthetic dataset using bi_wrapper.
rm(list = ls(all.names=TRUE))
unlink(".RData")
try(detach(package:bi, unload = TRUE), silent = TRUE)
library(bi, quietly = TRUE)

# the PZ model file is included in RBi and can be found there:
model_file_name <- system.file(package="bi", "PZ.bi")
PZ <- bi_model(model_file_name)
# the working folder is where the compiled files generated by LibBi will end up
working_folder <- normalizePath("~/")

T <- 50

init_file_name <- tempfile(pattern = "init", fileext=".nc")
init_parameters <- list(P = 2, Z = 2, mu = 0.5, sigma = 0.3)
bi_init_file(filename=init_file_name, variables=init_parameters)
# First let's generate a dataset from the model
synthetic_dataset <- bi_generate_dataset(endtime=T, model=PZ,
                                  working_folder=working_folder)
# Settings
bi_object <- bi_wrapper$new(client="sample", 
                            model=PZ, 
                            working_folder = working_folder,
                            global_options=list("obs-file" = synthetic_dataset,
                                                "init-file" = init_file_name))
print(bi_object)

# Once happy with the settings, launch bi.
bi_object$run(add_options = paste("--end-time", T, "--noutputs", T, "--nsamples 128 --nparticles 128 --verbose --nthreads 1"), 
              stdoutput_file_name = tempfile(pattern="pmmhoutput", fileext=".txt"))
# It can be a good idea to look at the result file
bi_file_summary(bi_object$result$output_file_name)
# Have a look at the posterior distribution
mu <- bi_read_var(bi_object$result$output_file_name, "mu")
g1 <- qplot(x = mu, y = ..density.., geom = "histogram") + xlab(expression(mu))
sigma <- bi_read_var(bi_object$result$output_file_name, "sigma")
g2 <- qplot(x = sigma, y = ..density.., geom = "histogram") + xlab(expression(sigma))
grid.arrange(g1, g2)
