// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nc_get_attributes_from_path
List nc_get_attributes_from_path(std::string path);
RcppExport SEXP bi_nc_get_attributes_from_path(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    std::string path = Rcpp::as<std::string >(pathSEXP);
    List __result = nc_get_attributes_from_path(path);
    return Rcpp::wrap(__result);
END_RCPP
}
