// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nc_create_netcdf_from_list_
void nc_create_netcdf_from_list_(std::string filename, List variables);
RcppExport SEXP bi_nc_create_netcdf_from_list_(SEXP filenameSEXP, SEXP variablesSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        std::string filename = Rcpp::as<std::string >(filenameSEXP);
        List variables = Rcpp::as<List >(variablesSEXP);
        nc_create_netcdf_from_list_(filename, variables);
    }
    return R_NilValue;
END_RCPP
}
// nc_get_attributes_from_path
List nc_get_attributes_from_path(std::string path);
RcppExport SEXP bi_nc_get_attributes_from_path(SEXP pathSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::string path = Rcpp::as<std::string >(pathSEXP);
        List __result = nc_get_attributes_from_path(path);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
