# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nc_create_init_file_ <- function(filename, variables) {
    invisible(.Call('bi_nc_create_init_file_', PACKAGE = 'bi', filename, variables))
}

nc_create_obs_file_ <- function(filename, dimension_name, variables) {
    invisible(.Call('bi_nc_create_obs_file_', PACKAGE = 'bi', filename, dimension_name, variables))
}

nc_get_attributes_from_path <- function(path) {
    .Call('bi_nc_get_attributes_from_path', PACKAGE = 'bi', path)
}

