# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nc_get_attributes_from_path <- function(path) {
    .Call('bi_nc_get_attributes_from_path', PACKAGE = 'bi', path)
}

